name: PR Preview Cleanup
on:
  pull_request:
    types: [ closed ]
  
jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - run: echo shutdown deployment

      - name: mark environment as deactivated
        uses: bobheadxi/deployments@v1
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: preview-${{ github.event.pull_request.number }}
          desc: PR was closed

      - name: Get token
        uses: tibdex/github-app-token@v1.8.0
        id: token
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_APP_PEM }}

      - name: delete environment
        uses: actions/github-script@v6
        env:
          ENVIRONMENT_TO_DELETE: preview-${{ github.event.pull_request.number }}
        with:
          github-token: "${{ steps.token.outputs.token }}"
          result-encoding: string
          script: |
              const { data } = await github.rest.repos.deleteAnEnvironment({
                ...context.repo,
                environment_name: process.env.ENVIRONMENT_TO_DELETE
              });
              console.log(data);

