name: PR Preview Cleanup
on:
  pull_request:
    types: [ closed ]
  
jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - run: echo shutdown deployment
      - uses: urcomputeringpal/preview-deploy-workflow-example@main
        with:
          step: cleanup
          env: preview-${{ github.event.pull_request.number }}
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_APP_PEM }}            

