name: PR Preview Cleanup
on:
  pull_request:
    types: [ closed ]
  
jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - run: echo shutdown deployment
      - name: Cleanup Preview deploy
        uses: urcomputeringpal/pr-preview-deploy-ux-action@main
        with:
          step: cleanup
          env: preview-${{ github.event.pull_request.number }}
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          app_pem: ${{ secrets.RENOVATE_APP_PEM }}            

