name: Rollout
on:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: 'true'

  rollout:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: ./
        name: Start preview deploy
        id: start
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          head_ref: ${{ github.head_ref }}
          env: rollout-${{ github.event.pull_request.number }}
          env_url: https://rollout-${{ github.event.pull_request.number }}.example.com
          log_url_job_name: rollout
          
      - run: echo perform deploy

      - uses: ./
        name: Finish preview deploy
        if: always()
        with:
          step: finish
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          head_ref: ${{ github.head_ref }}
          env: rollout-${{ github.event.pull_request.number }}

          deployment_id: ${{ steps.start.outputs.deployment_id }}
          env_url: https://rollout-${{ github.event.pull_request.number }}.example.com
          log_url_job_name: rollout
        